apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vilas-app-2
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: fluxcd-2022
  url: https://github.com/vilasvarghese/fluxcd_kustomize
  secretRef:
    name: vilas-app-2-github
