apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vilas-app-2
  namespace: default
spec:
  interval: 15m
  path: "./flux_java/deploy/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: vilas-app-2
